name: Backport Main → Staging

on:
  push:
    branches:
      - main
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  backport:
    runs-on: ubuntu-latest
#    outputs:
#      pr_number: ${{ steps.create-pr.outputs.pull-request-number }}
#      pr_url: ${{ steps.create-pr.outputs.pull-request-url }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for backporting

      - name: Backport to dev
        uses: korthout/backport-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: staging
          base_branch: main
          # Optional: Customize the title and body of the backport PR
          # title: 'Backport: ${{ github.event.pull_request.title }}'
          # body: 'This PR backports changes from #${{ github.event.pull_request.number }} to the `dev` branch.'
          # Optional: Specify cherry-picking behavior
          # cherry_picking: auto