name: Backport Main → Staging

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main   # ✅ always check out main

      - name: Fetch branches
        run: git fetch origin main staging --prune

      - name: Create Backport PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: staging   # PR target
          branch: backport/${{ github.run_id }}   # temporary backport branch
          title: "Backport changes from main to staging"
          body: |
            Automated backport PR to sync changes from **main** into **staging**.
