name: Backport Main → Staging

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: staging   # ✅ always check out main

      - name: Create/Update Backport PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main                      # Target branch for PR
          branch: backport/main-to-staging   # ✅ Fixed name → PR will be updated, not duplicated
          title: "Backport: Sync main → staging"
          body: |
            Automated backport PR to sync changes from **main** into **staging**.
          labels: |
            backport
            automated
