name: Backport Main → Staging

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  backporting:
    name: "Backporting"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Backporting
        uses: korthout/backport-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Secret token with repo write access
          branch_name: 'backport'
          target_branches: staging