name: Backport Main → Staging

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  backporting:
    name: "Backporting"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create backport PR
        uses: korthout/backport-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_name: 'backport/${pull_number}'
          target_branches: staging
          source_pr_number: ${{ github.event.pull_request.head.sha }}
          add_labels: BackPort
          add_author_as_assignee: true
          copy_requested_reviewers: true

