name: Backport Main → Staging

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  backporting:
    name: "Backporting"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Backporting
        uses: korthout/backport-action@v2
        with:
          github_token: ${{ secrets.BACKPORT_GITHUB_TOKEN }} # Secret token with repo write access
          branch_name: 'backport-${pull_number}-to-${target_branch}'
          target_branches: staging